config/routes.rb
Rails.application.routes.draw do
  resource :statistics, only: [:show]

  namespace :api do
    namespace :v1 do
      resources :messages, only: [:index, :create, :show] do
        patch :like, on: :member
      end
    end
  end

  scope :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
    end
  end

  root to: redirect('/statistics')
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :likeable, polymorphic: true, counter_cache: true
  belongs_to :user

  validates :user_id, uniqueness: { scope: [:likeable_type, :likeable_id] }
  validates :user, presence: true
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy

  validates :content, length: { maximum: 140 }, presence: true
  validates :user, presence: true

  scope :by_users, -> (users) { where(user_id: users.map(&:id)) }

  def like!(user)
    likes.create(user: user)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable
  include DeviseTokenAuth::Concerns::User

  has_many :messages, dependent: :destroy

  scope :by_messages_created_after, -> (datetime) { joins(:messages).where('messages.created_at > ?', datetime) }

  def self.by_messages_period(period)
    case period
    when 'day'
      by_messages_created_after(1.day.ago)
    when 'week'
      by_messages_created_after(1.week.ago)
    else
      all
    end
  end

  def self.by_messages_count
    select('users.*, COUNT(messages.id) AS messages_count')
      .joins(:messages)
      .group('users.id')
      .order('messages_count DESC')
  end

  def self.by_likes_count
    select('users.*, MAX(messages.likes_count) AS max_likes_count')
      .joins(:messages)
      .group('users.id')
      .order('max_likes_count DESC')
  end

  def self.by_likes_rating
    select('users.*, AVG(messages.likes_count) AS likes_rating')
      .joins(:messages)
      .group('users.id')
      .having('AVG(messages.likes_count) > 0')
      .order('likes_rating DESC')
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  include DeviseTokenAuth::Concerns::SetUserByToken
  protect_from_forgery with: :null_session
  respond_to :json

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private

  def record_not_found(error)
    render json: { errors: [error.message] }, status: :not_found
  end
end

app/controllers/api/v1/messages_controller.rb
class Api::V1::MessagesController < Api::V1::BaseController
  before_action :authenticate_user!, only: [:create, :like]
  before_action :set_message, only: [:like]

  def index
    @messages = Message.all
    respond_with @messages
  end

  def create
    @message = current_user.messages.create(message_params)
    respond_with :api, :v1, @message
  end

  def like
    @message.like!(current_user)
    render json: @message
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

  def set_message
    @message = Message.find(params[:id])
  end
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  has_scope :by_messages_period

  def show
    @users_by_messages = apply_scopes(User.by_messages_count).limit(5)

    @users_by_likes = apply_scopes(User.by_likes_count).limit(5)
    @messages_by_likes = Message.by_users(@users_by_likes).order(likes_count: :desc)

    @users_by_likes_rating = apply_scopes(User.by_likes_rating).limit(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html lang='ru'
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=edge'
    meta name='viewport' content='width=device-width, initial-scale=1'
    /title = t :app_name
    title LittleTwitter

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    / [if lt IE 9]
      script src='https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js'
      script src='https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js'

    = csrf_meta_tags
  body
    header

    .container
      = yield

app/views/statistics/show.html.slim
table.table
  caption = t('.table_caption_messages')
  thead
    th = User.model_name.human
    th = Message.model_name.human(count: 5)
  tbody
    - @users_by_messages.each do |user|
      tr
        td = user.email
        td = user.messages_count

table.table
  caption = t('.table_caption_likes')
  thead
    th = User.model_name.human
    th = Like.model_name.human(count: 5)
    th = Like.human_attribute_name(:content)
  tbody
    - @users_by_likes.each_with_index do |user, index|
      tr
        td = user.email
        td = @messages_by_likes[index].likes_count
        td = truncate(@messages_by_likes[index].content)

table.table
  caption = t('.table_caption_rating')
  thead
    th = User.model_name.human
    th = t('.likes_rating')
  tbody
    - @users_by_likes_rating.each_with_index do |user|
      tr
        td = user.email
        td = user.likes_rating

.pull-right
  = bootstrap_form_tag(url: statistics_path, method: :get, layout: :inline) do |f|
    = f.select 'by_messages_period', options_for_select([[t('.all_time'), :all], [t('.week'), :week], [t('.day'), :day]], selected: params[:by_messages_period]), label: t('.show_for_interval')
    = f.submit t('.update'), name: nil